### ISSUE TITLE
EvanG\Themes\LightTheme\LightTheme not found

### ISSUE THREAD

**Issue by hartenthaler** [06Games/Webtrees-ArgonLight#1]
After I downloaded ArgonLight from GitHub, I uploaded a copy to my webtrees modules_v4 directory. This results in an error:

`Fatal error in module: ArgonLight
Error: Class 'EvanG\Themes\LightTheme\LightTheme' not found in /xxx/webtrees/modules_v4/ArgonLight/module.php:15`

I didn't use composer or gulp. Should I? How?
Maybe some screenshots may help me to decide if I would like your theme or not. Or is there a demo installation somewhere available?

**Comment by 06Games** [comment]
I'm sorry you're experiencing an error with my theme
You shouldn't need to use composer and gulp, they are only used for development and SASS compilation 
Could you tell me if this version works for you [light.zip](https://github.com/06Games/Webtrees-ArgonLight/files/8287034/light.zip)

Here are some screenshots (I will update the readme):
![Capture d’écran 2022-03-17 à 14 43 10](https://user-images.githubusercontent.com/24252743/158822160-f4add63e-8bf5-47e6-a4f0-851db1eef4f9.png)
![Capture d’écran 2022-03-17 à 14 44 10](https://user-images.githubusercontent.com/24252743/158822147-c576c0cb-b5d0-416f-81b5-8a978f246374.png)
