### ISSUE TITLE
Overview of changes

### ISSUE THREAD

**Issue by heiler** [06Games/Webtrees-ArgonLight#12]
This overview is not readable (white on yellow), please see encl. screenshot.

![Screenshot 2023-04-10 at 10-16-39 – webtrees](https://user-images.githubusercontent.com/2920260/230862434-e7027ca2-dbdd-4443-ba56-f41cd4c7fe43.png)

**Comment by 06Games** [comment]
Thank you, this is now fixed
![firefox_9xdwyKlPrv](https://user-images.githubusercontent.com/24252743/230895280-0a23083e-a020-4d25-8540-17126186d487.png)
