### ISSUE TITLE
Conflict with Vesta Classic Look & Feel

### ISSUE THREAD

**Issue by hartenthaler** [06Games/Webtrees-ArgonLight#3]
My header area looks totally different compared to the nice header area in your screenshots. There is too much empty space. Ok, I can deactivate the FancyImageBar. What is the reason?

![Screenshot (84)](https://user-images.githubusercontent.com/6324175/158877795-c5436c8b-a744-467d-9a5d-f0b16f3190c0.png)

**Comment by 06Games** [comment]
It seems that the CSS is not fully loaded. May I ask what version of Webtrees you are using

**Comment by hartenthaler** [comment]
This was 2.0.21. Yes, I will disable all custom modules and remove all customized CSS code to check it then again.

**Comment by 06Games** [comment]
Hello, did you find the source of the problem?
I did some tests with a blank installation of Webtrees 2.1-beta1 and the theme works fine. So I think it's one of your modules that causes an incompatibility with the theme. If you find out what the module is, I may be able to fix this problem.

**Comment by hartenthaler** [comment]
This is a compatibility problem with the Vesta custom module "classic look and feel" (see https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf). When I disable this custom module ArgonLight looks great.

**Comment by 06Games** [comment]
Hello, thanks for the update
Indeed, this module modifies the default view, which I also do, and it prevents the CSS from being loaded.
Ideally, I would like to avoid overriding it (which would prevent this kind of conflict). I will see what I can do.
