### ISSUE TITLE
Footer: left-oriented versus centered

### ISSUE THREAD

**Issue by hartenthaler** [06Games/Webtrees-ArgonLight#4]
I cannot see the footer area in your screenshots. The first two lines in my footer are left-oriented, the others are centered, which looks strange.
![Screenshot (85)](https://user-images.githubusercontent.com/6324175/158879138-e5538185-1385-4ca4-9f82-2c3da00bfd80.png)

**Comment by 06Games** [comment]
I don't use footers, so I hadn't noticed the problem, thanks for pointing it out.
