### ISSUE TITLE
Search result list "shared places" is not formatted in correct style

### ISSUE THREAD

**Issue by hartenthaler** [06Games/Webtrees-ArgonLight#7]
Thanks for your very short response time! I like your theme.

If you like to show the "Shared places" list, the formatting is not ok.

![Screenshot (237)](https://user-images.githubusercontent.com/6324175/187952668-4172e631-1c78-45c6-a943-d5c4e556820d.png)

**Comment by 06Games** [comment]
I'm doing my best to answer as soon as possible, and I'm glad you like my theme ;)

The problem comes from a conflict on the name of a class (`.center`), it should be quite easy to fix.
