### ISSUE TITLE
Size of magnifying glass and links in chartbox unequal

### ISSUE THREAD

**Issue by arbor95** [06Games/Webtrees-ArgonLight#9]
Size of magnifying glass and links in chartbox is unequal.
The magnifying glass should be expanded for easier tap on small screen.

**Comment by arbor95** [comment]
the magnifying glass is still 12x12

**Comment by 06Games** [comment]
Which magnifying glass are you talking about?
For my part, the magnifying glass is 20x16 px
![image](https://user-images.githubusercontent.com/24252743/218117877-b8204499-d13d-4c4b-b496-1d899b84cf80.png)

**Comment by arbor95** [comment]
![size-small](https://user-images.githubusercontent.com/6124739/218119291-bf95b406-01b3-4f0e-8c7d-49c5a0501480.jpg)

perhaps have a look at freris.de .

hopfully i have overwritten with the latest version?

**Comment by 06Games** [comment]
Indeed, this is a problem with the Family tab (which I don't use, so I didn't notice it)
Thanks, I'll fix it
